# Generated by Django 5.2.11 on 2026-02-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('stay_minutes', models.PositiveIntegerField(null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourstop')),
            ],
        ),
    ]
