# Generated by Django 5.2.11 on 2026-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_routestop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='thumbnail',
            field=models.ImageField(blank=True, default='avatars/default.jpg', upload_to='thumbnails/'),
        ),
    ]
