# Generated by Django 5.2.11 on 2026-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstop',
            name='order',
        ),
    ]
