# Generated by Django 5.2.11 on 2026-02-12 00:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tourstop_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourroute',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
