# Generated by Django 5.2.11 on 2026-02-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourroute_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourroute',
            name='route',
        ),
    ]
