# Generated by Django 5.2.11 on 2026-02-12 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourroute_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourroute',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
