# Generated by Django 5.2.11 on 2026-02-12 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourroute_route'),
    ]

    operations = [
        migrations.RunSQL(sql=
            """
            -- 1. Tạo Function xử lý
                CREATE OR REPLACE FUNCTION update_tour_route_geometry()
                RETURNS TRIGGER AS $$
                DECLARE
                    route_geom GEOMETRY;
                BEGIN
                    -- Gom các điểm dừng thành đường LineString dựa trên thứ tự 'order'
                    -- Lưu ý: Phải JOIN với bảng TourStop để lấy tọa độ (geom)
                    SELECT ST_MakeLine(ts.geom ORDER BY rs.order)
                    INTO route_geom
                    FROM tours_routestop rs
                    JOIN tours_tourstop ts ON rs.stop_id = ts.id
                    WHERE rs.route_id = NEW.route_id;

                    -- Cập nhật vào bảng TourRoute
                    UPDATE tours_tourroute
                    SET route = route_geom,
                        distance_km = ST_Length(route_geom::geography) / 1000 
                    WHERE id = NEW.route_id;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                -- 2. Tạo Trigger
                CREATE TRIGGER trg_update_route_line
                AFTER INSERT OR UPDATE OR DELETE ON tours_routestop
                FOR EACH ROW
                EXECUTE FUNCTION update_tour_route_geometry();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_update_route_line ON tours_routestop;
                DROP FUNCTION IF EXISTS update_tour_route_geometry();
            """
        ),
    ]
