# Generated by Django 5.2.11 on 2026-02-12 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_routestop_trigger'),
    ]

    operations = [
        migrations.RunSQL(sql=
            """
            -- 1. Xóa nếu đã tồn tại để tránh lỗi khi chạy lại
                DROP TRIGGER IF EXISTS trg_update_route_line ON tours_routestop;
                DROP FUNCTION IF EXISTS update_tour_route_geometry();

                -- 2. Tạo Function xử lý
                CREATE OR REPLACE FUNCTION update_tour_route_geometry()
                RETURNS TRIGGER AS $$
                DECLARE
                    route_geom GEOMETRY;
                BEGIN
                    -- Lấy các điểm (location) từ TourStop, nối thành LineString theo thứ tự 'order'
                    -- Chuyển ::geometry vì ST_MakeLine làm việc với kiểu geometry
                    SELECT ST_MakeLine(ts.location::geometry ORDER BY rs."order")
                    INTO route_geom
                    FROM tours_routestop rs
                    JOIN tours_tourstop ts ON rs.stop_id = ts.id
                    WHERE rs.route_id = COALESCE(NEW.route_id, OLD.route_id);

                    -- Cập nhật vào bảng TourRoute
                    -- Nếu chỉ có 1 điểm hoặc không có điểm nào, route sẽ là NULL
                    UPDATE tours_tourroute
                    SET 
                        route = route_geom,
                        distance_km = CASE 
                            WHEN ST_NumPoints(route_geom) > 1 
                            THEN ST_Length(route_geom::geography) / 1000 
                            ELSE 0 
                        END
                    WHERE id = COALESCE(NEW.route_id, OLD.route_id);

                    RETURN NULL; -- AFTER trigger có thể return NULL
                END;
                $$ LANGUAGE plpgsql;

                -- 3. Tạo Trigger (Chạy sau khi data đã nằm trong RouteStop)
                CREATE TRIGGER trg_update_route_line
                AFTER INSERT OR UPDATE OR DELETE ON tours_routestop
                FOR EACH ROW
                EXECUTE FUNCTION update_tour_route_geometry();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_update_route_line ON tours_routestop;
                DROP FUNCTION IF EXISTS update_tour_route_geometry();
            """
        ),
    ]
