# Generated by Django 5.2.11 on 2026-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_update_routestop_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourstop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
