# Generated by Django 5.2.11 on 2026-02-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_continent_country_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.AddField(
            model_name='continent',
            name='code',
            field=models.CharField(default='VN', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.continent'),
        ),
    ]
