# Generated by Django 5.2.11 on 2026-02-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_remove_tour_location_continent_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.continent'),
        ),
    ]
