# Generated by Django 5.2.11 on 2026-02-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_continent_code_alter_country_continent'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP TRIGGER IF EXISTS trg_update_route_line
                ON tours_routestop;

                DROP FUNCTION IF EXISTS update_tour_route_geometry();
            """
        )
    ]
