# Generated by Django 5.2.11 on 2026-03-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_drop_trigger_routestop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourschedule',
            old_name='available_slots',
            new_name='total_slots',
        ),
    ]
